### ISSUE TITLE
Not able to install in iOS

### ISSUE THREAD

**Issue by jalanvikas** [duytq94/demo-integrate-react-native#3]
<img width="422" alt="Screenshot 2020-09-22 at 10 40 51 PM" src="https://user-images.githubusercontent.com/362193/93915134-2daab180-fd25-11ea-877d-40be1de0d13a.png">

**Comment by duytq94** [comment]
https://stackoverflow.com/questions/40327935/failed-to-load-info-plist-from-bundle
Seem this is not the project's issue, I'll close it, thanks.
